export { default as Header } from "./Header";
export { default as Contact } from "./Contact";
export { default as Overview } from "./Overview";
export { default as Skills } from "./Skills";
export { default as Experience } from "./Experience";
export { default as Education } from "./Education";
export { default as Certifications } from "./Certifications";
export { default as Achievements } from "./Achievements";
export { default as Projects } from "./Projects";
export { default as Extracurricular } from "./Extracurricular";
export { default as Volunteering } from "./Volunteering";
export { default as Publications } from "./Publications";
import "./styles.css";
